development:
  strategy: oauth
  oauth_consumer_key: <%= APP_CONFIG['twitter']['oauth_consumer_key'] %>
  oauth_consumer_secret: <%= APP_CONFIG['twitter']['oauth_consumer_key'] %>
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: <%= APP_CONFIG['twitter']['oauth_callback'] %>
test:
  strategy: oauth
  oauth_consumer_key: testkey
  oauth_consumer_secret: testsecret
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: <%= APP_CONFIG['twitter']['oauth_consumer_key'] %>
  oauth_consumer_secret: <%= APP_CONFIG['twitter']['oauth_consumer_key'] %>
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days
