name: ruby
"on":
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Ruby ${{ matrix.ruby }}"
    strategy:
      matrix:
        ruby:
          - 3.1.3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop
      - name: Run Rails tests
        run: bundle exec rails tests
      - name: Run specs
        run: bundle exec rspec
      - name: Run features
        run: bundle exec cucumber
